name: Bump Version

on: [push]
  branches:
    ['main']

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: python3 ./cicd_scripts/flutter_bump_version.py minor
      - run: echo "ğŸ This job's status is ${{ job.status }}."